const quizContent1_1 = {
  category: "Amerika",
  question: "In welcher Stadt steht die Freiheitsstatue?",
  answerA: "Boston",
  answerB: "New York City",
  answerC: "Chicago",
  answerD: "Miami",
  points: 10,
  correctAnswer: "answerB",
  questionIsActive: false,
  questionFinished: false,
};
const quizContent1_2 = {
  category: "Amerika",
  question: "Welche Farben hat die US-Flagge?",
  answerA: "Blau, Gelb, Rot",
  answerB: "Rot, Weiß, Blau",
  answerC: "Grün, Weiß, Rot",
  answerD: "Schwarz, Weiß, Rot",
  points: 20,
  correctAnswer: "answerB",
  questionIsActive: false,
  questionFinished: false,
};
const quizContent1_3 = {
  category: "Amerika",
  question: "Welches Tier ist das Nationalsymbol der USA?",
  answerA: "Grizzlybär",
  answerB: "Weißkopfseeadler",
  answerC: "Bison",
  answerD: "Puma",
  points: 30,
  correctAnswer: "answerB",
  questionIsActive: false,
  questionFinished: false,
};
const quizContent1_4 = {
  category: "Amerika",
  question: "Welcher Fluss ist der längste der USA?",
  answerA: "Colorado River",
  answerB: "Ohio River",
  answerC: "Missouri River",
  answerD: "Mississippi River",
  points: 40,
  correctAnswer: "answerC",
  questionIsActive: false,
  questionFinished: false,
};
const quizContent1_5 = {
  category: "Amerika",
  question:
    "In welchem Jahr wurde die Unabhängigkeitserklärung der USA unterzeichnet?",
  answerA: "1776",
  answerB: "1783",
  answerC: "1791",
  answerD: "1804",
  points: 50,
  correctAnswer: "answerA",
  questionIsActive: false,
  questionFinished: false,
};
const quizContent1_6 = {
  category: "Japan",
  question: "Welcher Berg ist der höchste in Japan?",
  answerA: "Norikura",
  answerB: "Fuji",
  answerC: "Tate",
  answerD: "Haku",
  points: 10,
  correctAnswer: "answerB",
  questionIsActive: false,
  questionFinished: false,
};
const quizContent1_7 = {
  category: "Japan",
  question: "Welche Währung wird in Japan verwendet?",
  answerA: "Yuan",
  answerB: "Won",
  answerC: "Yen",
  answerD: "Ringgit",
  points: 20,
  correctAnswer: "answerC",
  questionIsActive: false,
  questionFinished: false,
};
const quizContent1_8 = {
  category: "Japan",
  question:
    "Wie nennt man die japanische Kampfsportart, die „sanfter Weg“ bedeutet?",
  answerA: "Karate",
  answerB: "Kendo",
  answerC: "Aikido",
  answerD: "Judo",
  points: 30,
  correctAnswer: "answerD",
  questionIsActive: false,
  questionFinished: false,
};
const quizContent1_9 = {
  category: "Japan",
  question: "Wie nennt man die japanische Kunst des Papierfaltens?",
  answerA: "Kintsugi",
  answerB: "Origami",
  answerC: "Kirigami",
  answerD: "Kamon",
  points: 40,
  correctAnswer: "answerB",
  questionIsActive: false,
  questionFinished: false,
};
const quizContent1_10 = {
  category: "Japan",
  question:
    "Wie lautet das japanische Wort für einen wandernden, herrenlosen Samurai?",
  answerA: "Sensei",
  answerB: "Daimyō",
  answerC: "Ronin",
  answerD: "Shogun",
  points: 50,
  correctAnswer: "answerC",
  questionIsActive: false,
  questionFinished: false,
};
const quizContent1_11 = {
  category: "TV-Serien",
  question: "Welche Serie spielt auf dem fiktiven Kontinent Westeros?",
  answerA: "The Witcher",
  answerB: "Game of Thrones",
  answerC: "The Last Kingdom",
  answerD: "Vikings",
  points: 10,
  correctAnswer: "answerB",
  questionIsActive: false,
  questionFinished: false,
};
const quizContent1_12 = {
  category: "TV-Serien",
  question:
    "In „Breaking Bad“, wie heißt der Freund und Partner von Walter White?",
  answerA: "Gus Fring",
  answerB: "Jessie Pinkman",
  answerC: "Saul Goodman",
  answerD: "Hank Schrader",
  points: 20,
  correctAnswer: "answerB",
  questionIsActive: false,
  questionFinished: false,
};
const quizContent1_13 = {
  category: "TV-Serien",
  question:
    "Wie heißt der Bruder von Michael Scofield, der zu Beginn der Serie inhaftiert ist?",
  answerA: "Lincoln Burrows",
  answerB: "Paul Kellerman",
  answerC: "Terrence Steadman",
  answerD: "James Scofield",
  points: 30,
  correctAnswer: "answerA",
  questionIsActive: false,
  questionFinished: false,
};
const quizContent1_14 = {
  category: "TV-Serien",
  question: "In „Peaky Blinders“, wie heißt der Clanführer der Shelby-Familie?",
  answerA: "John Shelby",
  answerB: "Arthur Shelby",
  answerC: "Tommy Shelby",
  answerD: "Michael Gray",
  points: 40,
  correctAnswer: "answerC",
  questionIsActive: false,
  questionFinished: false,
};
const quizContent1_15 = {
  category: "TV-Serien",
  question:
    "In „Loki“, wie heißt die Organisation, die Zeitkriminalität überwacht?",
  answerA: "TVA",
  answerB: "HYDRA",
  answerC: "SHIELD",
  answerD: "SWORD",
  points: 50,
  correctAnswer: "answerA",
  questionIsActive: false,
  questionFinished: false,
};
const quizContent1_16 = {
  category: "Römer",
  question: "Wer war der erste Kaiser von Rom?",
  answerA: "Julius Caesar",
  answerB: "Augustus",
  answerC: "Nero",
  answerD: "Trajan",
  points: 10,
  correctAnswer: "answerB",
  questionIsActive: false,
  questionFinished: false,
};
const quizContent1_17 = {
  category: "Römer",
  question: "Was war das Forum Romanum?",
  answerA: "Ein römisches Theater",
  answerB: "Ein Marktplatz und politisches Zentrum",
  answerC: "Eine Gladiatorenarena",
  answerD: "Eine römische Bibliothek",
  points: 20,
  correctAnswer: "answerB",
  questionIsActive: false,
  questionFinished: false,
};
const quizContent1_18 = {
  category: "Römer",
  question:
    "Welches berühmte Bauwerk wurde von Kaiser Vespasian in Rom erbaut?",
  answerA: "Das Kolosseum",
  answerB: "Der Circus Maximus",
  answerC: "Der Pantheon",
  answerD: "Das Forum Romanum",
  points: 30,
  correctAnswer: "answerA",
  questionIsActive: false,
  questionFinished: false,
};
const quizContent1_19 = {
  category: "Römer",
  question: "Wie hieß die römische Göttin der Weisheit und des Krieges?",
  answerA: "Venus",
  answerB: "Mars",
  answerC: "Minerva",
  answerD: "Juno",
  points: 40,
  correctAnswer: "answerC",
  questionIsActive: false,
  questionFinished: false,
};
const quizContent1_20 = {
  category: "Römer",
  question:
    "Wie hieß der berühmte römische Architekt, der unter Augustus das Pantheon baute?",
  answerA: "Vitruvius",
  answerB: "Apollodorus von Damaskus",
  answerC: "Marcus Agrippa",
  answerD: "Pliny der Jüngere",
  points: 50,
  correctAnswer: "answerC",
  questionIsActive: false,
  questionFinished: false,
};
const quizContent1_21 = {
  category: "Bekannte Personen",
  question: "Wer gründete Microsoft?",
  answerA: "Bill Gates",
  answerB: "Steve Jobs",
  answerC: "Ronald Wayne",
  answerD: "Satya Nadella",
  points: 10,
  correctAnswer: "answerA",
  questionIsActive: false,
  questionFinished: false,
};
const quizContent1_22 = {
  category: "Bekannte Personen",
  question: "Wie heißt der bekannte Mitbegründer von Apple neben Steve Jobs?",
  answerA: "Jeff Bezos",
  answerB: "Paul Allen",
  answerC: "Bill Gates",
  answerD: "Steve Wozniak",
  points: 20,
  correctAnswer: "answerD",
  questionIsActive: false,
  questionFinished: false,
};
const quizContent1_23 = {
  category: "Bekannte Personen",
  question: "Wer ist bekannt als das Orakel von Omaha?",
  answerA: "Jerome H. Powell",
  answerB: "Ray Dalio",
  answerC: "Warren Buffet",
  answerD: "Carl Icahn",
  points: 30,
  correctAnswer: "answerC",
  questionIsActive: false,
  questionFinished: false,
};
const quizContent1_24 = {
  category: "Bekannte Personen",
  question: "Wer entdeckte Radium und gewann zwei Nobelpreise?",
  answerA: "Isaac Newton",
  answerB: "Albert Einstein",
  answerC: "Marie Curie",
  answerD: "Stephen Hawking",
  points: 40,
  correctAnswer: "answerC",
  questionIsActive: false,
  questionFinished: false,
};
const quizContent1_25 = {
  category: "Bekannte Personen",
  question:
    "Wer spielt die Hauptrolle in dem Film „From the World of John Wick: Ballerina“?",
  answerA: "Jodie Foster",
  answerB: "Camila Cabello",
  answerC: "Margot Robbie",
  answerD: "Ana de Armas",
  points: 50,
  correctAnswer: "answerD",
  questionIsActive: false,
  questionFinished: false,
};
const quizContent2_1 = {
  category: "Philosophie",
  question: "Von welchem Philosoph stammt das Werk „Die Republik“?",
  answerA: "Aristoteles",
  answerB: "Nietzsche",
  answerC: "Platon",
  answerD: "Mark Twain",
  points: 10,
  correctAnswer: "answerC",
  questionIsActive: false,
  questionFinished: false,
};
const quizContent2_2 = {
  category: "Philosophie",
  question: "Was ist die Ethik?",
  answerA: "Moralisch richtigen Handelns",
  answerB: "Die Glaubwürdigkeit des Redners",
  answerC: "Antike Heilmethoden",
  answerD: "Das gleiche wie Esoterik",
  points: 20,
  correctAnswer: "answerA",
  questionIsActive: false,
  questionFinished: false,
};
const quizContent2_3 = {
  category: "Philosophie",
  question: "Von welchem Philosophen stammt das stoische Werk „Meditations“?",
  answerA: "Sokrates",
  answerB: "Epictetus",
  answerC: "Seneca",
  answerD: "Marcus Aurelius",
  points: 30,
  correctAnswer: "answerD",
  questionIsActive: false,
  questionFinished: false,
};
const quizContent2_4 = {
  category: "Philosophie",
  question: "Was ist der Solipsismus?",
  answerA: "Das Konzept das nur man selbst sicher existiert",
  answerB: "Wenn man seine Einsamkeit genießt",
  answerC: "Wenn man alleine etwas durchsteht",
  answerD: "Das Konzept das man durch Einsamkeit neue Ideen hat",
  points: 40,
  correctAnswer: "answerA",
  questionIsActive: false,
  questionFinished: false,
};
const quizContent2_5 = {
  category: "Philosophie",
  question: "Was bedeutet „Cogito, ergo sum“?",
  answerA: "Kognitive Fähigkeiten zählen",
  answerB: "Ich denke, also bin ich",
  answerC: "Ich denke, es ist eine Summe",
  answerD: "Kognitive Fähigkeiten, werden siegen",
  points: 50,
  correctAnswer: "answerB",
  questionIsActive: false,
  questionFinished: false,
};
const quizContent2_6 = {
  category: "Informatik",
  question: "Welches Programm braucht man um auf eine Website gehen zu können?",
  answerA: "Distributor",
  answerB: "Office 365",
  answerC: "Word",
  answerD: "Browser",
  points: 10,
  correctAnswer: "answerD",
  questionIsActive: false,
  questionFinished: false,
};
const quizContent2_7 = {
  category: "Informatik",
  question: "Welches Datenkabel hat die höchste Übertragungsleistung?",
  answerA: "Audiokabel",
  answerB: "Koaxialkabel",
  answerC: "Glasfaser",
  answerD: "HDMI Kabel",
  points: 20,
  correctAnswer: "answerC",
  questionIsActive: false,
  questionFinished: false,
};
const quizContent2_8 = {
  category: "Informatik",
  question: "Was ist das „Moor’sche Gesetz“?",
  answerA:
    "Prozessoren verdoppeln etwa alle 18–24 Monate ihre Leistungsfähigkeit",
  answerB: "Prozessoren verbrauchen mit der Zeit weniger Strom",
  answerC: "Prozessoren werden nur größer, nicht schneller",
  answerD: "Prozessoren bekommen alle vier Jahre neue Transistoren",
  points: 30,
  correctAnswer: "answerA",
  questionIsActive: false,
  questionFinished: false,
};
const quizContent2_9 = {
  category: "Informatik",
  question: "Warum wurde JavaScript so genannt wie es heißt?",
  answerA: "Aus Marketinggründen",
  answerB: "Weil es vom gleichen Macher ist wie Java",
  answerC: "Weil dem Entwickler die Idee dazu auf der Insel Java kam",
  answerD: "Weil es so ähnlich zu Java ist",
  points: 40,
  correctAnswer: "answerA",
  questionIsActive: false,
  questionFinished: false,
};
const quizContent2_10 = {
  category: "Informatik",
  question:
    "Wenn man einen Downloadspeed von 50Mbit/s hat und eine 100MB Datei runterlädt, wie lange dauert das?",
  answerA: "16 Sekunden",
  answerB: "2 Sekunden",
  answerC: "1 Sekunden",
  answerD: "4 Sekunden",
  points: 50,
  correctAnswer: "answerA",
  questionIsActive: false,
  questionFinished: false,
};
const quizContent2_11 = {
  category: "Skurriles",
  question: "Welches Tier kann beim Schlafen „stehen bleiben“ ohne Umzufallen?",
  answerA: "Armeisenbär",
  answerB: "Faultiere",
  answerC: "Elefanten",
  answerD: "Koalas",
  points: 10,
  correctAnswer: "answerA",
  questionIsActive: false,
  questionFinished: false,
};
const quizContent2_12 = {
  category: "Skurriles",
  question:
    "Der Mitbegründer von welchem Unternehmen hat sein Hühnchen „zwangskanibalisiert“?",
  answerA: "Amazon",
  answerB: "Enron",
  answerC: "Meta",
  answerD: "Netflix",
  points: 20,
  correctAnswer: "answerC",
  questionIsActive: false,
  questionFinished: false,
};
const quizContent2_13 = {
  category: "Skurriles",
  question: "Welches Tier heißt „Firefox“?",
  answerA: "Ein roter Fuchs",
  answerB: "Ein roter Armeisenbär",
  answerC: "Ein roter Panda",
  answerD: "Ein rotes Faultier",
  points: 30,
  correctAnswer: "answerC",
  questionIsActive: false,
  questionFinished: false,
};
const quizContent2_14 = {
  category: "Skurriles",
  question: "Welche Essens-Kuriosität ist tatsächlich wahr?",
  answerA: "Kartoffeln wurden früher als Dessert gegessen",
  answerB: "Karotten waren ursprünglich lila",
  answerC: "Tomaten gab es zuerst in blau",
  answerD: "Brokkoli ist ein Wildgemüse",
  points: 40,
  correctAnswer: "answerB",
  questionIsActive: false,
  questionFinished: false,
};
const quizContent2_15 = {
  category: "Skurriles",
  question: "Welches Land hat offiziell einen Trident auf seiner Flagge?",
  answerA: "Andorra",
  answerB: "Nepal",
  answerC: "Barbados",
  answerD: "Laos",
  points: 50,
  correctAnswer: "answerC",
  questionIsActive: false,
  questionFinished: false,
};
const quizContent2_16 = {
  category: "Geschichte",
  question: "Wie viele Jahre liegen zwischen dem ersten und zweiten Weltkrieg?",
  answerA: "21",
  answerB: "23",
  answerC: "31",
  answerD: "33",
  points: 10,
  correctAnswer: "answerA",
  questionIsActive: false,
  questionFinished: false,
};
const quizContent2_17 = {
  category: "Geschichte",
  question:
    "Was waren die ersten nicht von Pferden angetriebenen Fahrzeuge oder Wagen?",
  answerA: "Elektro Fahrzeuge",
  answerB: "Verbrennungsmotor Fahrzeuge",
  answerC: "Dampfwagen",
  answerD: "Der Schlitten vom Weihnachtsmann",
  points: 20,
  correctAnswer: "answerC",
  questionIsActive: false,
  questionFinished: false,
};
const quizContent2_18 = {
  category: "Geschichte",
  question: "Wo wurde die Demokratie erfunden?",
  answerA: "In Babylon",
  answerB: "In Washington DC",
  answerC: "In Neapel",
  answerD: "In Athen",
  points: 30,
  correctAnswer: "answerD",
  questionIsActive: false,
  questionFinished: false,
};
const quizContent2_19 = {
  category: "Geschichte",
  question: "Wer umsegelte als erster Mensch die Erde?",
  answerA: "Ferdinand Magellan",
  answerB: "Christoph Kolumbus",
  answerC: "Nikolaus Kopernikus",
  answerD: "James Cook",
  points: 40,
  correctAnswer: "answerA",
  questionIsActive: false,
  questionFinished: false,
};
const quizContent2_20 = {
  category: "Geschichte",
  question: "Wo kämpften die 300 Spartaner gegen die Perser?",
  answerA: "Mykene",
  answerB: "Korinth",
  answerC: "Thermopylen",
  answerD: "Delphi",
  points: 50,
  correctAnswer: "answerC",
  questionIsActive: false,
  questionFinished: false,
};
const quizContent2_21 = {
  category: "Zitate",
  question:
    "Von wem stammt folgendes Zitat: „Sei ängstlich, wenn die anderen gierig sind, und gierig, wenn die anderen ängstlich sind.“?",
  answerA: "Rothschild",
  answerB: "Warren Buffet",
  answerC: "Jesse Livermore",
  answerD: "André Kostolany",
  points: 10,
  correctAnswer: "answerB",
  questionIsActive: false,
  questionFinished: false,
};
const quizContent2_22 = {
  category: "Zitate",
  question:
    "Von wem stammt folgendes Zitat: „Das Ganze ist mehr als die Summe seiner Teile“?",
  answerA: "Sokrates",
  answerB: "Aristoteles",
  answerC: "Mark Twain",
  answerD: "Platon",
  points: 20,
  correctAnswer: "answerB",
  questionIsActive: false,
  questionFinished: false,
};
const quizContent2_23 = {
  category: "Zitate",
  question: "Von wem stammt folgendes Zitat: „Wollt ihr den totalen Krieg“?",
  answerA: "Adolf Hitler",
  answerB: "Bernd Ernst",
  answerC: "Joseph Goebbels",
  answerD: "Theodor Morell",
  points: 30,
  correctAnswer: "answerC",
  questionIsActive: false,
  questionFinished: false,
};
const quizContent2_24 = {
  category: "Zitate",
  question:
    "Von wem stammt folgendes Zitat: „Sei du selbst die Veränderung, die du dir wünschst für diese Welt.“?",
  answerA: "Mahatma Gandhi",
  answerB: "Martin Luther King",
  answerC: "Nelson Mandela",
  answerD: "Galileo Galilei",
  points: 40,
  correctAnswer: "answerA",
  questionIsActive: false,
  questionFinished: false,
};
const quizContent2_25 = {
  category: "Zitate",
  question:
    "Von wem stammt folgendes Zitat: „Ich habe nie einen Plan B gehabt. Plan A ist der einzige Weg.“?",
  answerA: "Angelina Jolie",
  answerB: "Keanu Reeves",
  answerC: "Will Smith",
  answerD: "Henry Ford",
  points: 50,
  correctAnswer: "answerC",
  questionIsActive: false,
  questionFinished: false,
};
const quizContent3_1 = {
  category: "Filme",
  question: "question",
  answerA: "AnswerA",
  answerB: "AnswerB",
  answerC: "AnswerC",
  answerD: "AnswerD",
  points: 10,
  correctAnswer: "answerA",
  questionIsActive: false,
  questionFinished: false,
};
const quizContent3_2 = {
  category: "Japan",
  question: "question",
  answerA: "AnswerA",
  answerB: "AnswerB",
  answerC: "AnswerC",
  answerD: "AnswerD",
  points: 20,
  correctAnswer: "answerA",
  questionIsActive: false,
  questionFinished: false,
};
const quizContent3_3 = {
  category: "Japan",
  question: "question",
  answerA: "AnswerA",
  answerB: "AnswerB",
  answerC: "AnswerC",
  answerD: "AnswerD",
  points: 30,
  correctAnswer: "answerA",
  questionIsActive: false,
  questionFinished: false,
};
const quizContent3_4 = {
  category: "Japan",
  question: "question",
  answerA: "AnswerA",
  answerB: "AnswerB",
  answerC: "AnswerC",
  answerD: "AnswerD",
  points: 40,
  correctAnswer: "answerA",
  questionIsActive: false,
  questionFinished: false,
};
const quizContent3_5 = {
  category: "Japan",
  question: "question",
  answerA: "AnswerA",
  answerB: "AnswerB",
  answerC: "AnswerC",
  answerD: "AnswerD",
  points: 50,
  correctAnswer: "answerA",
  questionIsActive: false,
  questionFinished: false,
};
const quizContent3_6 = {
  category: "Japan",
  question: "question",
  answerA: "AnswerA",
  answerB: "AnswerB",
  answerC: "AnswerC",
  answerD: "AnswerD",
  points: 10,
  correctAnswer: "answerA",
  questionIsActive: false,
  questionFinished: false,
};
const quizContent3_7 = {
  category: "Japan",
  question: "question",
  answerA: "AnswerA",
  answerB: "AnswerB",
  answerC: "AnswerC",
  answerD: "AnswerD",
  points: 20,
  correctAnswer: "answerA",
  questionIsActive: false,
  questionFinished: false,
};
const quizContent3_8 = {
  category: "Japan",
  question: "question",
  answerA: "AnswerA",
  answerB: "AnswerB",
  answerC: "AnswerC",
  answerD: "AnswerD",
  points: 30,
  correctAnswer: "answerA",
  questionIsActive: false,
  questionFinished: false,
};
const quizContent3_9 = {
  category: "Japan",
  question: "question",
  answerA: "AnswerA",
  answerB: "AnswerB",
  answerC: "AnswerC",
  answerD: "AnswerD",
  points: 40,
  correctAnswer: "answerA",
  questionIsActive: false,
  questionFinished: false,
};
const quizContent3_10 = {
  category: "Japan",
  question: "question",
  answerA: "AnswerA",
  answerB: "AnswerB",
  answerC: "AnswerC",
  answerD: "AnswerD",
  points: 50,
  correctAnswer: "answerA",
  questionIsActive: false,
  questionFinished: false,
};
const quizContent3_11 = {
  category: "Japan",
  question: "question",
  answerA: "AnswerA",
  answerB: "AnswerB",
  answerC: "AnswerC",
  answerD: "AnswerD",
  points: 10,
  correctAnswer: "answerA",
  questionIsActive: false,
  questionFinished: false,
};
const quizContent3_12 = {
  category: "Japan",
  question: "question",
  answerA: "AnswerA",
  answerB: "AnswerB",
  answerC: "AnswerC",
  answerD: "AnswerD",
  points: 20,
  correctAnswer: "answerA",
  questionIsActive: false,
  questionFinished: false,
};
const quizContent3_13 = {
  category: "Japan",
  question: "question",
  answerA: "AnswerA",
  answerB: "AnswerB",
  answerC: "AnswerC",
  answerD: "AnswerD",
  points: 30,
  correctAnswer: "answerA",
  questionIsActive: false,
  questionFinished: false,
};
const quizContent3_14 = {
  category: "Japan",
  question: "question",
  answerA: "AnswerA",
  answerB: "AnswerB",
  answerC: "AnswerC",
  answerD: "AnswerD",
  points: 40,
  correctAnswer: "answerA",
  questionIsActive: false,
  questionFinished: false,
};
const quizContent3_15 = {
  category: "Japan",
  question: "question",
  answerA: "AnswerA",
  answerB: "AnswerB",
  answerC: "AnswerC",
  answerD: "AnswerD",
  points: 50,
  correctAnswer: "answerA",
  questionIsActive: false,
  questionFinished: false,
};
const quizContent3_16 = {
  category: "Japan",
  question: "question",
  answerA: "AnswerA",
  answerB: "AnswerB",
  answerC: "AnswerC",
  answerD: "AnswerD",
  points: 10,
  correctAnswer: "answerA",
  questionIsActive: false,
  questionFinished: false,
};
const quizContent3_17 = {
  category: "Japan",
  question: "question",
  answerA: "AnswerA",
  answerB: "AnswerB",
  answerC: "AnswerC",
  answerD: "AnswerD",
  points: 20,
  correctAnswer: "answerA",
  questionIsActive: false,
  questionFinished: false,
};
const quizContent3_18 = {
  category: "Japan",
  question: "question",
  answerA: "AnswerA",
  answerB: "AnswerB",
  answerC: "AnswerC",
  answerD: "AnswerD",
  points: 30,
  correctAnswer: "answerA",
  questionIsActive: false,
  questionFinished: false,
};
const quizContent3_19 = {
  category: "Japan",
  question: "question",
  answerA: "AnswerA",
  answerB: "AnswerB",
  answerC: "AnswerC",
  answerD: "AnswerD",
  points: 40,
  correctAnswer: "answerA",
  questionIsActive: false,
  questionFinished: false,
};
const quizContent3_20 = {
  category: "Japan",
  question: "question",
  answerA: "AnswerA",
  answerB: "AnswerB",
  answerC: "AnswerC",
  answerD: "AnswerD",
  points: 50,
  correctAnswer: "answerA",
  questionIsActive: false,
  questionFinished: false,
};
const quizContent3_21 = {
  category: "Japan",
  question: "question",
  answerA: "AnswerA",
  answerB: "AnswerB",
  answerC: "AnswerC",
  answerD: "AnswerD",
  points: 10,
  correctAnswer: "answerA",
  questionIsActive: false,
  questionFinished: false,
};
const quizContent3_22 = {
  category: "Japan",
  question: "question",
  answerA: "AnswerA",
  answerB: "AnswerB",
  answerC: "AnswerC",
  answerD: "AnswerD",
  points: 20,
  correctAnswer: "answerA",
  questionIsActive: false,
  questionFinished: false,
};
const quizContent3_23 = {
  category: "Japan",
  question: "question",
  answerA: "AnswerA",
  answerB: "AnswerB",
  answerC: "AnswerC",
  answerD: "AnswerD",
  points: 30,
  correctAnswer: "answerA",
  questionIsActive: false,
  questionFinished: false,
};
const quizContent3_24 = {
  category: "Japan",
  question: "question",
  answerA: "AnswerA",
  answerB: "AnswerB",
  answerC: "AnswerC",
  answerD: "AnswerD",
  points: 40,
  correctAnswer: "answerA",
  questionIsActive: false,
  questionFinished: false,
};
const quizContent3_25 = {
  category: "Japan",
  question: "question",
  answerA: "AnswerA",
  answerB: "AnswerB",
  answerC: "AnswerC",
  answerD: "AnswerD",
  points: 50,
  correctAnswer: "answerA",
  questionIsActive: false,
  questionFinished: false,
};
export const quizData = [
  {
    isActive: false,
    isSelected: false,
    quizStarted: false,
    name: "Jeopardy 1",
    madeBy: "Katja, Fredy und Oli",
    activePlayer: 1,
    content: [
      quizContent1_1,
      quizContent1_2,
      quizContent1_3,
      quizContent1_4,
      quizContent1_5,
      quizContent1_6,
      quizContent1_7,
      quizContent1_8,
      quizContent1_9,
      quizContent1_10,
      quizContent1_11,
      quizContent1_12,
      quizContent1_13,
      quizContent1_14,
      quizContent1_15,
      quizContent1_16,
      quizContent1_17,
      quizContent1_18,
      quizContent1_19,
      quizContent1_20,
      quizContent1_21,
      quizContent1_22,
      quizContent1_23,
      quizContent1_24,
      quizContent1_25,
    ],
  },
  {
    isActive: false,
    isSelected: false,
    quizStarted: false,
    name: "Jeopardy 2",
    madeBy: "Oli",
    activePlayer: 1,
    content: [
      quizContent2_1,
      quizContent2_2,
      quizContent2_3,
      quizContent2_4,
      quizContent2_5,
      quizContent2_6,
      quizContent2_7,
      quizContent2_8,
      quizContent2_9,
      quizContent2_10,
      quizContent2_11,
      quizContent2_12,
      quizContent2_13,
      quizContent2_14,
      quizContent2_15,
      quizContent2_16,
      quizContent2_17,
      quizContent2_18,
      quizContent2_19,
      quizContent2_20,
      quizContent2_21,
      quizContent2_22,
      quizContent2_23,
      quizContent2_24,
      quizContent2_25,
    ],
  },
  {
    isActive: false,
    isSelected: false,
    quizStarted: false,
    name: "Jeopardy 3",
    madeBy: "unfinished",
    activePlayer: 1,
    content: [
      quizContent3_1,
      quizContent3_2,
      quizContent3_3,
      quizContent3_4,
      quizContent3_5,
      quizContent3_6,
      quizContent3_7,
      quizContent3_8,
      quizContent3_9,
      quizContent3_10,
      quizContent3_11,
      quizContent3_12,
      quizContent3_13,
      quizContent3_14,
      quizContent3_15,
      quizContent3_16,
      quizContent3_17,
      quizContent3_18,
      quizContent3_19,
      quizContent3_20,
      quizContent3_21,
      quizContent3_22,
      quizContent3_23,
      quizContent3_24,
      quizContent3_25,
    ],
  },
];
